
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADD ALTER AND AT BASE COLUMN COMMA COMPARE CREATE DATA DATE DECIMAL DECIMALES DIFFERENT DIVIDE EQUAL FROM GREATER GREATER_EQUAL ID INSERT INT INTO KEY LESS LESS_EQUAL LPAREN MINUS NOT NOT_EQUAL NOT_SYMBOL NULL NUMBER NVARCHAR OR PERIOD PLUS PRIMARY REFERENCE RPAREN SELECT SEMICOLOM STRING TABLE TIMES USE VALUES WHEREinit : statement init\n            | statement\n            statement : create_database\n                | use_database\n                | create_table\n                \n                create_database : CREATE DATA BASE ID SEMICOLOMuse_database : USE ID SEMICOLOM\n    create_table : CREATE TABLE ID LPAREN columns RPAREN SEMICOLOM\n    \n    columns : columns COMMA column\n            | column\n\n    column : ID type attributes\n\n    \n    type : INT\n         | DATE\n         | NVARCHAR LPAREN NUMBER RPAREN\n         | DECIMAL\n    \n    attributes : attributes attribute\n               | attribute\n    \n    attribute : PRIMARY KEY\n              | REFERENCE ID LPAREN ID RPAREN\n              | nullable\n    \n    nullable : NOT NULL\n             | empty\n    empty :'
    
_lr_action_items = {'CREATE':([0,2,3,4,5,14,17,36,],[6,6,-3,-4,-5,-7,-6,-8,]),'USE':([0,2,3,4,5,14,17,36,],[7,7,-3,-4,-5,-7,-6,-8,]),'$end':([1,2,3,4,5,8,14,17,36,],[0,-2,-3,-4,-5,-1,-7,-6,-8,]),'DATA':([6,],[9,]),'TABLE':([6,],[10,]),'ID':([7,10,12,16,27,31,43,],[11,13,15,18,18,40,45,]),'BASE':([9,],[12,]),'SEMICOLOM':([11,15,26,],[14,17,36,]),'LPAREN':([13,24,40,],[16,35,43,]),'INT':([18,],[22,]),'DATE':([18,],[23,]),'NVARCHAR':([18,],[24,]),'DECIMAL':([18,],[25,]),'RPAREN':([19,20,21,22,23,25,28,29,32,34,37,38,39,41,42,44,45,46,],[26,-10,-23,-12,-13,-15,-11,-17,-20,-22,-9,-16,-18,-21,44,-14,46,-19,]),'COMMA':([19,20,21,22,23,25,28,29,32,34,37,38,39,41,44,46,],[27,-10,-23,-12,-13,-15,-11,-17,-20,-22,-9,-16,-18,-21,-14,-19,]),'PRIMARY':([21,22,23,25,28,29,32,34,38,39,41,44,46,],[30,-12,-13,-15,30,-17,-20,-22,-16,-18,-21,-14,-19,]),'REFERENCE':([21,22,23,25,28,29,32,34,38,39,41,44,46,],[31,-12,-13,-15,31,-17,-20,-22,-16,-18,-21,-14,-19,]),'NOT':([21,22,23,25,28,29,32,34,38,39,41,44,46,],[33,-12,-13,-15,33,-17,-20,-22,-16,-18,-21,-14,-19,]),'KEY':([30,],[39,]),'NULL':([33,],[41,]),'NUMBER':([35,],[42,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'init':([0,2,],[1,8,]),'statement':([0,2,],[2,2,]),'create_database':([0,2,],[3,3,]),'use_database':([0,2,],[4,4,]),'create_table':([0,2,],[5,5,]),'columns':([16,],[19,]),'column':([16,27,],[20,37,]),'type':([18,],[21,]),'attributes':([21,],[28,]),'attribute':([21,28,],[29,38,]),'nullable':([21,28,],[32,32,]),'empty':([21,28,],[34,34,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> init","S'",1,None,None,None),
  ('init -> statement init','init',2,'p_init','parser.py',14),
  ('init -> statement','init',1,'p_init','parser.py',15),
  ('statement -> create_database','statement',1,'p_statement','parser.py',20),
  ('statement -> use_database','statement',1,'p_statement','parser.py',21),
  ('statement -> create_table','statement',1,'p_statement','parser.py',22),
  ('create_database -> CREATE DATA BASE ID SEMICOLOM','create_database',5,'p_create_database','parser.py',30),
  ('use_database -> USE ID SEMICOLOM','use_database',3,'p_use_database','parser.py',39),
  ('create_table -> CREATE TABLE ID LPAREN columns RPAREN SEMICOLOM','create_table',7,'p_create_table','parser.py',47),
  ('columns -> columns COMMA column','columns',3,'p_columns','parser.py',52),
  ('columns -> column','columns',1,'p_columns','parser.py',53),
  ('column -> ID type attributes','column',3,'p_columns','parser.py',55),
  ('type -> INT','type',1,'p_type','parser.py',61),
  ('type -> DATE','type',1,'p_type','parser.py',62),
  ('type -> NVARCHAR LPAREN NUMBER RPAREN','type',4,'p_type','parser.py',63),
  ('type -> DECIMAL','type',1,'p_type','parser.py',64),
  ('attributes -> attributes attribute','attributes',2,'p_attributes','parser.py',69),
  ('attributes -> attribute','attributes',1,'p_attributes','parser.py',70),
  ('attribute -> PRIMARY KEY','attribute',2,'p_attribute','parser.py',75),
  ('attribute -> REFERENCE ID LPAREN ID RPAREN','attribute',5,'p_attribute','parser.py',76),
  ('attribute -> nullable','attribute',1,'p_attribute','parser.py',77),
  ('nullable -> NOT NULL','nullable',2,'p_nullable','parser.py',82),
  ('nullable -> empty','nullable',1,'p_nullable','parser.py',83),
  ('empty -> <empty>','empty',0,'p_empty','parser.py',89),
]
